services:
  aerocache-api:
    container_name: aerocache-api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5200:5200"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5200
    restart: always

  aerocache-web:
    container_name: aerocache-web
    build:
      context: ./aerocache-web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - aerocache-api
    restart: always

